// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonaScript.Modules.Scripts.Infrastructure.Persistence;

#nullable disable

namespace PersonaScript.Modules.Scripts.Infrastructure.Migrations
{
    [DbContext(typeof(ScriptsDbContext))]
    partial class ScriptsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scripts")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonaScript.Modules.Scripts.Domain.NinetyDayCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnamneseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("GeradoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ObjetivoTrimestral")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("PersonaDiagnosisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("NinetyDayCalendars", "scripts");
                });

            modelBuilder.Entity("PersonaScript.Modules.Scripts.Domain.StoryPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnamneseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DiretrizesHumanizacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrequenciaDiariaRecomendada")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("GeradoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("PersonaDiagnosisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("StoryPlans", "scripts");
                });

            modelBuilder.Entity("PersonaScript.Modules.Scripts.Domain.VideoScript", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnamneseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ChamadaParaAcao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DicasGravacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("FeedbackAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FeedbackNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedbackRating")
                        .HasColumnType("int");

                    b.Property<string>("Gancho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("GeradoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LegendaSugerida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("PersonaDiagnosisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PilarConteudo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Retencao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TomVozAplicado")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("VideoScripts", "scripts");
                });

            modelBuilder.Entity("PersonaScript.Modules.Scripts.Domain.NinetyDayCalendar", b =>
                {
                    b.OwnsMany("PersonaScript.Modules.Scripts.Domain.ValueObjects.WeeklyEditorialPlan", "Semanas", b1 =>
                        {
                            b1.Property<Guid>("NinetyDayCalendarId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.PrimitiveCollection<string>("IdeiasConteudo")
                                .IsRequired();

                            b1.Property<int>("NumeroSemana");

                            b1.Property<string>("ObjetivoEstrategico")
                                .IsRequired();

                            b1.Property<string>("PilarConteudo")
                                .IsRequired();

                            b1.Property<string>("SugestaoFormato")
                                .IsRequired();

                            b1.Property<string>("TemaCentral")
                                .IsRequired();

                            b1.HasKey("NinetyDayCalendarId", "__synthesizedOrdinal");

                            b1.ToTable("NinetyDayCalendars", "scripts");

                            b1
                                .ToJson("Semanas")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("NinetyDayCalendarId");
                        });

                    b.Navigation("Semanas");
                });

            modelBuilder.Entity("PersonaScript.Modules.Scripts.Domain.StoryPlan", b =>
                {
                    b.OwnsMany("PersonaScript.Modules.Scripts.Domain.ValueObjects.StoryBlock", "BlocosHorarios", b1 =>
                        {
                            b1.Property<Guid>("StoryPlanId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("ExemploPratico")
                                .IsRequired();

                            b1.Property<string>("GatilhoRotina")
                                .IsRequired();

                            b1.Property<string>("HorarioSugestao")
                                .IsRequired();

                            b1.Property<string>("ObjetivoConexao")
                                .IsRequired();

                            b1.Property<string>("Periodo")
                                .IsRequired();

                            b1.Property<string>("TipoConteudo")
                                .IsRequired();

                            b1.HasKey("StoryPlanId", "__synthesizedOrdinal");

                            b1.ToTable("StoryPlans", "scripts");

                            b1
                                .ToJson("BlocosHorarios")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("StoryPlanId");
                        });

                    b.Navigation("BlocosHorarios");
                });
#pragma warning restore 612, 618
        }
    }
}
