// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonaScript.Modules.Anamnese.Infrastructure.Persistence;

#nullable disable

namespace PersonaScript.Modules.Anamnese.Infrastructure.Migrations
{
    [DbContext(typeof(AnamneseDbContext))]
    partial class AnamneseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("anamnese")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonaScript.Modules.Anamnese.Domain.Anamnese", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ConcluidoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("EtapaAtual")
                        .HasColumnType("int");

                    b.Property<int>("PercentualConclusao")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Anamneses", "anamnese");
                });

            modelBuilder.Entity("PersonaScript.Modules.Anamnese.Domain.Anamnese", b =>
                {
                    b.OwnsOne("PersonaScript.Modules.Anamnese.Domain.ValueObjects.Etapa10Objetivos", "Etapa10", b1 =>
                        {
                            b1.Property<Guid>("AnamneseId");

                            b1.Property<string>("ExperienciaPassadaMarketing")
                                .IsRequired();

                            b1.Property<string>("Meta1Ano")
                                .IsRequired();

                            b1.Property<string>("Meta3Meses")
                                .IsRequired();

                            b1.Property<int>("ResultadoPrioritario");

                            b1.HasKey("AnamneseId");

                            b1.ToTable("Anamneses", "anamnese");

                            b1
                                .ToJson("Etapa10")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("AnamneseId");
                        });

                    b.OwnsOne("PersonaScript.Modules.Anamnese.Domain.ValueObjects.Etapa1QuemEVoce", "Etapa1", b1 =>
                        {
                            b1.Property<Guid>("AnamneseId");

                            b1.Property<string>("ComoGostaSerChamado")
                                .IsRequired();

                            b1.Property<string>("FormacoesEspecializacoes")
                                .IsRequired();

                            b1.Property<int>("MomentoAtual");

                            b1.Property<string>("NomeCompleto")
                                .IsRequired();

                            b1.Property<int>("PacientesMes");

                            b1.Property<string>("PremiosTitulos")
                                .IsRequired();

                            b1.Property<string>("ProfissaoEspecialidade")
                                .IsRequired();

                            b1.Property<int>("TempoAtuacaoAnos");

                            b1.HasKey("AnamneseId");

                            b1.ToTable("Anamneses", "anamnese");

                            b1
                                .ToJson("Etapa1")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("AnamneseId");
                        });

                    b.OwnsOne("PersonaScript.Modules.Anamnese.Domain.ValueObjects.Etapa2SuaHistoria", "Etapa2", b1 =>
                        {
                            b1.Property<Guid>("AnamneseId");

                            b1.Property<string>("CasoMarcante")
                                .IsRequired();

                            b1.Property<string>("FaseMaisDificil")
                                .IsRequired();

                            b1.Property<string>("MotivacaoEscolha")
                                .IsRequired();

                            b1.Property<string>("MotorPessoal")
                                .IsRequired();

                            b1.HasKey("AnamneseId");

                            b1.ToTable("Anamneses", "anamnese");

                            b1
                                .ToJson("Etapa2")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("AnamneseId");
                        });

                    b.OwnsOne("PersonaScript.Modules.Anamnese.Domain.ValueObjects.Etapa3SeuTrabalho", "Etapa3", b1 =>
                        {
                            b1.Property<Guid>("AnamneseId");

                            b1.Property<string>("CriticaAosPares")
                                .IsRequired();

                            b1.Property<string>("DiferencialAtendimento")
                                .IsRequired();

                            b1.Property<string>("PorQueEscolhemVoce")
                                .IsRequired();

                            b1.Property<string>("ProcedimentoLucrativo")
                                .IsRequired();

                            b1.Property<string>("ProcedimentoMaster")
                                .IsRequired();

                            b1.Property<string>("ProcedimentoPreferido")
                                .IsRequired();

                            b1.HasKey("AnamneseId");

                            b1.ToTable("Anamneses", "anamnese");

                            b1
                                .ToJson("Etapa3")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("AnamneseId");
                        });

                    b.OwnsOne("PersonaScript.Modules.Anamnese.Domain.ValueObjects.Etapa4SeuPaciente", "Etapa4", b1 =>
                        {
                            b1.Property<Guid>("AnamneseId");

                            b1.Property<int>("CanalOrigem");

                            b1.Property<string>("MaioresDesejos")
                                .IsRequired();

                            b1.Property<string>("MaioresMedos")
                                .IsRequired();

                            b1.Property<string>("MitosInformacoesErradas")
                                .IsRequired();

                            b1.Property<string>("PerfilDemograficoPsicografico")
                                .IsRequired();

                            b1.Property<string>("PerguntasFrequentes")
                                .IsRequired();

                            b1.HasKey("AnamneseId");

                            b1.ToTable("Anamneses", "anamnese");

                            b1
                                .ToJson("Etapa4")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("AnamneseId");
                        });

                    b.OwnsOne("PersonaScript.Modules.Anamnese.Domain.ValueObjects.Etapa5SuasReferencias", "Etapa5", b1 =>
                        {
                            b1.Property<Guid>("AnamneseId");

                            b1.Property<string>("OQueAdmiraArea")
                                .IsRequired();

                            b1.Property<string>("OQueAtraiForaArea")
                                .IsRequired();

                            b1.Property<string>("OQueNaoFariaArea")
                                .IsRequired();

                            b1.Property<string>("PerfisArea")
                                .IsRequired();

                            b1.Property<string>("PerfisForaArea")
                                .IsRequired();

                            b1.HasKey("AnamneseId");

                            b1.ToTable("Anamneses", "anamnese");

                            b1
                                .ToJson("Etapa5")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("AnamneseId");
                        });

                    b.OwnsOne("PersonaScript.Modules.Anamnese.Domain.ValueObjects.Etapa6LimitesExposicao", "Etapa6", b1 =>
                        {
                            b1.Property<Guid>("AnamneseId");

                            b1.Property<string>("AssuntosProibidos")
                                .IsRequired();

                            b1.Property<string>("EstiloVidaAceito")
                                .IsRequired();

                            b1.Property<int>("NivelConfortoCamera");

                            b1.Property<string>("RegrasConselhoRegional")
                                .IsRequired();

                            b1.Property<string>("TrabalhoAceito")
                                .IsRequired();

                            b1.Property<string>("VidaPessoalAceita")
                                .IsRequired();

                            b1.HasKey("AnamneseId");

                            b1.ToTable("Anamneses", "anamnese");

                            b1
                                .ToJson("Etapa6")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("AnamneseId");
                        });

                    b.OwnsOne("PersonaScript.Modules.Anamnese.Domain.ValueObjects.Etapa7SeuConhecimento", "Etapa7", b1 =>
                        {
                            b1.Property<Guid>("AnamneseId");

                            b1.Property<string>("ConteudoDosSonhos")
                                .IsRequired();

                            b1.Property<string>("PostsDeuCerto")
                                .IsRequired();

                            b1.Property<string>("PostsNaoFuncionaram")
                                .IsRequired();

                            b1.Property<string>("TemaPalestra")
                                .IsRequired();

                            b1.Property<string>("TemasFavoritos")
                                .IsRequired();

                            b1.Property<string>("VerdadeCorajosa")
                                .IsRequired();

                            b1.HasKey("AnamneseId");

                            b1.ToTable("Anamneses", "anamnese");

                            b1
                                .ToJson("Etapa7")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("AnamneseId");
                        });

                    b.OwnsOne("PersonaScript.Modules.Anamnese.Domain.ValueObjects.Etapa8SeuJeito", "Etapa8", b1 =>
                        {
                            b1.Property<Guid>("AnamneseId");

                            b1.Property<string>("AmostraEscritaExplicativa")
                                .IsRequired();

                            b1.Property<string>("ArquetiposComunicacao")
                                .IsRequired();

                            b1.Property<string>("EsteticaOdiada")
                                .IsRequired();

                            b1.Property<string>("IdentidadeVisualStatus")
                                .IsRequired();

                            b1.HasKey("AnamneseId");

                            b1.ToTable("Anamneses", "anamnese");

                            b1
                                .ToJson("Etapa8")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("AnamneseId");
                        });

                    b.OwnsOne("PersonaScript.Modules.Anamnese.Domain.ValueObjects.Etapa9RotinaCapacidade", "Etapa9", b1 =>
                        {
                            b1.Property<Guid>("AnamneseId");

                            b1.Property<string>("ApoioDisponivel")
                                .IsRequired();

                            b1.Property<string>("DiaTipicoRotina")
                                .IsRequired();

                            b1.Property<string>("HistoricoPostagensUltimaSemana")
                                .IsRequired();

                            b1.Property<string>("HorasSemanaConteudo")
                                .IsRequired();

                            b1.Property<string>("RankingFacilidadeFormatos")
                                .IsRequired();

                            b1.HasKey("AnamneseId");

                            b1.ToTable("Anamneses", "anamnese");

                            b1
                                .ToJson("Etapa9")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("AnamneseId");
                        });

                    b.Navigation("Etapa1");

                    b.Navigation("Etapa10");

                    b.Navigation("Etapa2");

                    b.Navigation("Etapa3");

                    b.Navigation("Etapa4");

                    b.Navigation("Etapa5");

                    b.Navigation("Etapa6");

                    b.Navigation("Etapa7");

                    b.Navigation("Etapa8");

                    b.Navigation("Etapa9");
                });
#pragma warning restore 612, 618
        }
    }
}
