// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonaScript.Modules.Personas.Infrastructure.Persistence;

#nullable disable

namespace PersonaScript.Modules.Personas.Infrastructure.Migrations
{
    [DbContext(typeof(PersonasDbContext))]
    [Migration("20260819004626_InitialPersonas")]
    partial class InitialPersonas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("personas")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PersonaScript.Modules.Personas.Domain.PersonaDiagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnamneseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FrasePosicionamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("GeradoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SintesePerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("PersonaDiagnoses", "personas");
                });

            modelBuilder.Entity("PersonaScript.Modules.Personas.Domain.PersonaDiagnosis", b =>
                {
                    b.OwnsOne("PersonaScript.Modules.Personas.Domain.ValueObjects.IdentidadeMarca", "IdentidadeMarca", b1 =>
                        {
                            b1.Property<Guid>("PersonaDiagnosisId");

                            b1.Property<string>("ArquetipoPrincipal")
                                .IsRequired();

                            b1.Property<string>("ArquetipoSecundario")
                                .IsRequired();

                            b1.Property<string>("EstiloVisualSugerido")
                                .IsRequired();

                            b1.Property<string>("TomDeVoz")
                                .IsRequired();

                            b1.HasKey("PersonaDiagnosisId");

                            b1.ToTable("PersonaDiagnoses", "personas");

                            b1
                                .ToJson("IdentidadeMarca")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PersonaDiagnosisId");
                        });

                    b.OwnsOne("PersonaScript.Modules.Personas.Domain.ValueObjects.MatrizRestricoes", "MatrizRestricoes", b1 =>
                        {
                            b1.Property<Guid>("PersonaDiagnosisId");

                            b1.PrimitiveCollection<string>("DiretrizesInegociaveis")
                                .IsRequired();

                            b1.Property<string>("LimitesExposicao")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("PalavrasEvitar")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("TemasProibidos")
                                .IsRequired();

                            b1.HasKey("PersonaDiagnosisId");

                            b1.ToTable("PersonaDiagnoses", "personas");

                            b1
                                .ToJson("MatrizRestricoes")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PersonaDiagnosisId");
                        });

                    b.OwnsMany("PersonaScript.Modules.Personas.Domain.ValueObjects.PilarConteudo", "PilaresConteudo", b1 =>
                        {
                            b1.Property<Guid>("PersonaDiagnosisId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAddOrUpdate();

                            b1.Property<string>("Descricao")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("ExemplosTopicos")
                                .IsRequired();

                            b1.Property<string>("Nome")
                                .IsRequired();

                            b1.Property<int>("Percentual");

                            b1.HasKey("PersonaDiagnosisId", "__synthesizedOrdinal");

                            b1.ToTable("PersonaDiagnoses", "personas");

                            b1
                                .ToJson("PilaresConteudo")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("PersonaDiagnosisId");
                        });

                    b.Navigation("IdentidadeMarca")
                        .IsRequired();

                    b.Navigation("MatrizRestricoes")
                        .IsRequired();

                    b.Navigation("PilaresConteudo");
                });
#pragma warning restore 612, 618
        }
    }
}
